export interface IInput {
  fieldcatalogno: string;
  cocode: string;
  processcode: string;
  transactioncode: string;
  userid: string;
  inputlength: number;
  controlwidth: number;
  labelwidth: number;
  anchor: string;
  tabindex: number;
  controltype: string;
  applicationdatatype: string;
  ontooltip: boolean;
  onlabel: boolean;
  visible: number;
  disable: number;
  enbaftrclick: number;
  attachmentrequired: boolean;
  quickfactrequired: boolean;
  quickfacts: null;
  opendocrequired: boolean;
  opendoc: string | null;
  helpobject: string;
  reportobject: string;
  flexobject: string;
  fieldid: string;
  dropdown: number;
  helpwhere: string;
  displaytexttable: string;
  baseonsql: boolean;
  baseontable: boolean;
  displayhelpobject: string;
  fielddisplay: string;
  fieldwhere: string;
  sql: string;
  label: string | null;
  helpobjectlang: string;
  reportobjectlang: string;
  flexobjectlang: string;
  defaultvalue: string;
  ismandatorybeforecreate: boolean;
  ismandatoryaftercreate: boolean;
  subform: boolean;
  toolbarkey: string;
  langno: string;
  financialdimensionrequired: boolean;
}
